<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * @property string name
 * @property string group_name
 */
class Permission extends Model
{

    const ADMIN_CREATE_PROVIDER = 1;
    const ADMIN_UPDATE_PROVIDER = 2;
    const ADMIN_CREATE_MERCHANT = 3;
    const ADMIN_UPDATE_MERCHANT = 4;
    const ADMIN_UPDATE_USER_CHANNEL_ACCOUNT = 5;
    const ADMIN_DESTROY_USER_CHANNEL_ACCOUNT = 6;
    const ADMIN_UPDATE_TRANSACTION = 7;
    const ADMIN_CREATE_SYSTEM_BANK_CARD = 8;
    const ADMIN_UPDATE_SYSTEM_BANK_CARD = 9;
    const ADMIN_DESTROY_SYSTEM_BANK_CARD = 10;
    const ADMIN_UPDATE_DEPOSIT = 11;
    const ADMIN_UPDATE_WITHDRAW = 12;
    const ADMIN_UPDATE_USER_BANK_CARD = 13;
    const ADMIN_DESTROY_USER_BANK_CARD = 14;
    const ADMIN_UPDATE_CHANNEL = 15;
    const ADMIN_UPDATE_FEATURE_TOGGLE = 16;
    const ADMIN_UPDATE_PROVIDER_WALLET = 17;
    const ADMIN_UPDATE_MERCHANT_WALLET = 18;
    const ADMIN_MANAGE_WHITELISTED_IP = 19;
    const ADMIN_MANAGE_TIME_LIMIT_BANK = 20;
    const ADMIN_MANAGE_MATCHING_DEPOSIT_REWARD = 21;
    const ADMIN_MANAGE_TRANSACTION_REWARD = 22;
    const ADMIN_MANAGE_PROVIDER_WHITELISTED_IP = 23;
    const ADMIN_MANAGE_MERCHANT_LOGIN_WHITELISTED_IP = 24;
    const ADMIN_MANAGE_MERCHANT_API_WHITELISTED_IP = 25;
    const ADMIN_MANAGE_MERCHANT_MATCHING_DEPOSIT_GROUPS = 26;
    const ADMIN_MANAGE_MERCHANT_TRANSACTION_GROUPS = 27;
    const ADMIN_MANAGE_BANNED_IP = 28;
    const ADMIN_MANAGE_MERCHANT_THIRD_CHANNEL = 29;
    const ADMIN_MANAGE_MERCHANT_SECRET = 30;
    const ADMIN_MANAGE_ANNOUNCEMENT = 31;
    const ADMIN_CREATE_FILL_IN_ORDER = 32;
    const ADMIN_FINANCIAL_REPORT = 33;
    const ADMIN_SHOW_SENSITIVE_DATA = 34;
    const ADMIN_INTERNAL_TRANSFER = 35;

    protected $fillable = ['role', 'group_name', 'name'];
}
