<?php


namespace App\Utils;


class ThirdPartyResponseUtil
{
    const ERROR_CODE_INSUFFICIENT_BALANCE = 1;
    const ERROR_CODE_WITHDRAW_DISABLED = 2;
    const ERROR_CODE_BAD_REQUEST = 3;
    const ERROR_CODE_USER_NOT_FOUND = 4;
    const ERROR_CODE_INVALID_SIGN = 5;
    const ERROR_CODE_RACE_CONDITION = 6;
    const ERROR_CODE_TRANSACTION_NOT_FOUND = 7;
    const ERROR_CODE_DUPLICATE_ORDER_NUMBER = 8;
    const ERROR_CODE_AGENCY_WITHDRAW_DISABLED = 9;
    const ERROR_CODE_INVALID_MIN_AMOUNT = 10;
    const ERROR_CODE_INVALID_MAX_AMOUNT = 11;
    const ERROR_CODE_INVALID_CHANNEL_CODE = 12;
    const ERROR_CODE_CHANNEL_TEMPORARY_UNAVAILABLE = 13;
    const ERROR_CODE_TRANSACTION_DISABLED = 14;
    const ERROR_CODE_INVALID_AMOUNT = 15;
    const ERROR_CODE_BUSY_PAYING = 16;
    const ERROR_CODE_NO_AVAILABLE_USER_CHANNEL_ACCOUNT_FOR_TRANSACTION = 17;
    const ERROR_CODE_INVALID_IP = 18;
    const ERROR_CODE_PLEASE_RETRY_FOR_ANOTHER_MATCHING = 19;
    const ERROR_CODE_CURRENT_STATUS_CANNOT_RETRY = 20;
    const ERROR_CODE_PAYING_TIMED_OUT = 21;
    const ERROR_CODE_BANK_NOT_FOUND = 22;
    const ERROR_CODE_FORBIDDEN_NAME = 23;
}
